#ifndef AMDAHL_SRC_DOMAIN_SOLVER_MEMETIC_CROSSOVER_CROSSOVER_STRATEGY_H_
#define AMDAHL_SRC_DOMAIN_SOLVER_MEMETIC_CROSSOVER_CROSSOVER_STRATEGY_H_

enum class CrossoverStrategy {
    kSrex = 0,
    kEax,
};
#endif